### ISSUE TITLE
Newly registered user is not registered to projects

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#36]
If you add a user with my new management view but that user is not registered.. they will not be hooked to the project until they visit the project (which they can't, there's no links...).

So really the `project_access_required` is really useless. I'm tempted to break them out into different files at this point (instead of one big v1_api_ file we get like mulitple files, like project.py, todo.py.. etc etc.)

Though I would have to wait until our current PR gets merged to do so.

**Comment by shuhaowu** [comment]
ping @travellingprog: thoughts?

**Comment by travellingprog** [comment]
I do think that it would be a good idea to split the API into multiple files.

It seems to me that if the user can't see a link to the project from when he visits `/app`, then the issue is with the `@route("/", methods=["GET"])` method in ProjectsView, which doesn't have a `project_access_required` decorator, so I don't understand why you think that decorator is useless.

As a side note, is there a command that allows me to explore the levelubpDB from Terminal?

**Comment by shuhaowu** [comment]
Don't explore levelupdb in the terminal. It's not ready yet. Just try riak :P levelupdb, in theory, should be a drop in replacement.

Also, this has been fixed by #39
