### ISSUE TITLE
With filters on right now, adding a todo will bring up an invalid pagination bar.

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#5]
This might be invalid if we implement pagination for filtering and sorting.

Steps to reproduce:
1. Filter for some tag (checking/unchecking any of the filter will do)
2. Add/delete a todo.
3. Observe the bottom of the page has a invalid pagination bar.

This part of the code is pretty fugly. So yeah.

**Comment by travellingprog** [comment]
I think I've fixed this (just issues with the `filter` function), but I have questions regarding the `recomputePages` function. 
1. Why would `totalPages` ever be null after that calculation?
2. What's the point of `$scope.pages`? I see that you're building an array of number that would go from 1 to max 7, and you don't seem to use it anywhere in your code.

It just looks like leftover code that should be deleted and that I can remove for my next pull request.

**Comment by shuhaowu** [comment]
1. The filter do not have pagination (maybe we need to fix this) and it sets `totalPages` to `null`. See https://github.com/shuhaowu/projecto/blob/master/static/js/develop/controllers/todos.js#L251
2. `$scope.pages` is actually used in the template. There is no other way to loop through just numbers with angular other than this (I think. If there is a way, feel free to change it.)

**Comment by travellingprog** [comment]
1. Yeah, filters definitely need pagination. It's because you were setting `totalPages` to `null` that this bug existed. I thought you had made a mistake. Think I'll add pagination to filters then. It's just an inconsistent experience if you go from having pagination to none IMO.
2. Oh, I see, you use it in the pagination template logic. I was searching for $scope.pages. Yeah, check [the issue I just opened](https://github.com/shuhaowu/projecto/issues/27), I totally think I can make the pagination template simpler. But i'll do that after closing this issue.

**Comment by shuhaowu** [comment]
Another good idea would be pagination with a directive.

Shuhao

**Comment by shuhaowu** [comment]
Fixed by #34
